/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Motto: typeof import('./src/components/Motto.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TimeCapsule: typeof import('./src/components/TimeCapsule.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
  }
}
